# Homework 1: Transition from NumPy to PyTorch

Name: Chenthuran Abeyakaran

Wustlkey: cjabeyakaran

Partner Name (if applicable):

Partner Wustlkey (if applicable):

### Submission instructions

- Submit the modified python notebook as homework submission.
- Group submission is enabled, you can submit this coding assignment with up to 1 teammate in our class. For instruction of how to do a group submission. Please refer to Canvas useful links.
- Do not change the number of cells! Please work in the cell provided. If we need extra cells for debugging and testing purposes, we can work at the end of this notebook, save everything as a backup for review, and delete the extra cells in the submitted version.

 

### Instructions
Do **not** use for loops in any of our solutions! Efficieny will be graded as well. For example if a problem asks us generate an array from 0 to 9: then
```python
x = []
for i in range(10):
    x.append(i)
```
this will only result a partial credit while
```python
x = np.arange(10)
```
or
```python
x = torch.arange(10)
```
will yield a full score.

### Problems
Below are 6 problems that explore different common used tools in Numpy and how to translate them into Torch codes. Each problem gives examples demonstrating the concept and has an associated coding task. Complete the coding tasks for credit.

### Grading
This homework has 6 problems, 4 points each for problem 1-5 and 10 points for the last problem. The homework will be graded and the grade counts towards your course grade. The homework will weigh 50% compared to the subsequent assignemnts (it's not fully weighted...). 

## Coding environments and submission
If we do not have `torch` installed on your computer, we have three ways to upload this notebook to [Google colab](https://colab.research.google.com/)：

1. Open up Google Colab, choose `Upload` to upload this template and work there. After we have done working we can select `File->Download .ipynb`.
2. Open up Google Colab, choose either `GitHub` or `Google Drive` to select the uploaded notebook in the corresponding website. After done working, we can sync the file to the corresponding GitHub or Google Drive copy.

In [1]:
# Run Me First
import numpy as np
import torch

## 1D Basic Array Functions
### Examples

In [2]:
arr1 = torch.tensor([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [3]:
# Accessing elements
print(arr1[0])
print(arr1[3])

tensor(55.7000)
tensor(75.7000)


In [4]:
#Slicing
print(arr1[0:3])
print(arr1[:3])
print(arr1[17:])
print(arr1[:])

tensor([55.7000, 51.4000, 50.5000])
tensor([55.7000, 51.4000, 50.5000])
tensor([58.4000, 70.4000, 41.2000])
tensor([55.7000, 51.4000, 50.5000, 75.7000, 58.4000, 40.1000, 61.5000, 57.1000,
        60.9000, 66.6000, 60.4000, 68.1000, 66.9000, 53.4000, 48.6000, 56.8000,
        71.6000, 58.4000, 70.4000, 41.2000])


In [5]:
#Element Types
print(arr1.dtype)
print(torch.tensor([0, 1, 2, 3]).dtype)
print(torch.tensor([1.0, 1.5, 2.0, 2.5]).dtype)
print(torch.tensor([1.0, 1.5, 2.0, 2.5], dtype=torch.float64).dtype)
print(torch.tensor([True, False, True]).dtype)

torch.float32
torch.int64
torch.float32
torch.float64
torch.bool


In [6]:
# Looping - AVOID THIS!

for i in range(len(arr1)):
    element = arr1[i]
    print(f'Array {i}-th entry has value {element}')

Array 0-th entry has value 55.70000076293945
Array 1-th entry has value 51.400001525878906
Array 2-th entry has value 50.5
Array 3-th entry has value 75.69999694824219
Array 4-th entry has value 58.400001525878906
Array 5-th entry has value 40.099998474121094
Array 6-th entry has value 61.5
Array 7-th entry has value 57.099998474121094
Array 8-th entry has value 60.900001525878906
Array 9-th entry has value 66.5999984741211
Array 10-th entry has value 60.400001525878906
Array 11-th entry has value 68.0999984741211
Array 12-th entry has value 66.9000015258789
Array 13-th entry has value 53.400001525878906
Array 14-th entry has value 48.599998474121094
Array 15-th entry has value 56.79999923706055
Array 16-th entry has value 71.5999984741211
Array 17-th entry has value 58.400001525878906
Array 18-th entry has value 70.4000015258789
Array 19-th entry has value 41.20000076293945


In [7]:
# (Almost) Every numpy functions has it torch counterparts
print(arr1.mean())
print(arr1.std())
print(arr1.max())
print(arr1.sum())

tensor(58.6850)
tensor(9.5809)
tensor(75.7000)
tensor(1173.7000)


### Problem 1

Fill in the following cell to calculate the maximum of the first half (first `len(arr1)//2` elements) and the second half of the array using slicing and the built-in `max()` method.

In [8]:
# your code here
max_1st_half = arr1[: len(arr1)//2].max()
max_2nd_half = arr1[len(arr1)//2: ].max()

print(f"Max of the 1st half: {max_1st_half}; Max of the 2nd half: {max_2nd_half}")

Max of the 1st half: 75.69999694824219; Max of the 2nd half: 71.5999984741211


## 1D Arithmetic and Logic
### Examples

In [9]:
# Arithmetic operations between 2 torch tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([1, 2, 1, 2])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

tensor([2, 4, 4, 6])
tensor([0, 0, 2, 2])
tensor([1, 4, 3, 8])
tensor([1, 1, 3, 2])
tensor([ 1,  4,  3, 16])


/tmp/pip-req-build-w9kte7xz/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.


In [10]:
# Arithmetic operations between a torch tensor and a single number  
a = torch.tensor([1, 2, 3, 4])
b = 2

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

tensor([3, 4, 5, 6])
tensor([-1,  0,  1,  2])
tensor([2, 4, 6, 8])
tensor([0, 1, 1, 2])
tensor([ 1,  4,  9, 16])


In [11]:
# Logical operations with torch tensors
a = torch.tensor([True, True, False, False])
b = torch.tensor([True, False, True, False])

print(a & b)
print(a | b)
print(~a)

print(a & True)
print(a & False)

print(a | True)
print(a | False)

tensor([ True, False, False, False])
tensor([ True,  True,  True, False])
tensor([False, False,  True,  True])
tensor([ True,  True, False, False])
tensor([False, False, False, False])
tensor([True, True, True, True])
tensor([ True,  True, False, False])


In [12]:
# Comparison operations of torch tensors to a number
a = torch.tensor([1, 2, 3, 4])
b = 2
    
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a != b)

tensor([False, False,  True,  True])
tensor([False,  True,  True,  True])
tensor([ True, False, False, False])
tensor([ True,  True, False, False])
tensor([False,  True, False, False])
tensor([ True, False,  True,  True])


### Problem 2
Fill in this section to compute a `torch.tensor` containing the average of the two given arrays to achieve the effect of the following `for` loop:
```python
avg = []
for i in range(len(arr1)):
    avg.append((arr1[i] + arr2[i])/2)
```

In [13]:
arr1 = torch.tensor([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

arr2 = torch.tensor([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

'''
    
'''

# your code here
arr_avg = (arr1 + arr2)/2

print(arr_avg)

tensor([ 96.4160, 102.6443, 101.4113,  93.3163, 103.4556,  98.1482, 102.3511,
         91.7785,  92.8355,  89.6558,  99.2187,  98.4843,  94.1728, 117.3351,
         98.2756,  33.0404,  41.9052,  90.9630,  57.0840,  93.0602])


## 1D Boolean (Fancy and Fast) Indexing
###  Examples

In [14]:
# Using index arrays
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([True, True, False, False])
    
print(a[b])
print(a[torch.tensor([True, False, True, False])])

tensor([1, 2])
tensor([1, 3])


In [15]:
# Creating the index array using vectorized operations (Recall ReLU implemented in class)
a = torch.tensor([1, 2, 3, 2, 1])
b = (a >= 2)
    
print(a[b])
print(a[a >= 2])

tensor([2, 3, 2])
tensor([2, 3, 2])


In [16]:
# Creating the index array using vectorized operations on another array
a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([1, 2, 3, 2, 1])
    
print(b == 2)
print(a[b == 2])

tensor([False,  True, False,  True, False])
tensor([2, 4])


### Problem 3

Fill in the following cell using the boolean indexing vectorization technique to calculate an array that can be achieved using the following `for` loop:
```python
result = []
for i in range(len(arr1)):
    if arr1[i] < 60:
        result.append(arr2[i])

```

In [17]:
arr1 = torch.tensor([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

arr2 = torch.tensor([4,   5,  37,   3,  12,   
                 4,  35,  38,   5,  37,   
                 3,   3,  68,  38,  98,   
                 2, 249,   2, 127,  35])

'''

'''

# your code here
result = arr2[arr1 < 60]

print(result)    

tensor([  4,   5,   3,  12,   4,  35,  38,  37,   3,   3,  68,   2, 249,   2,
        127,  35])


## 2D Basic Functions: Indexing, Axis
### Example 1

In [18]:
mat1 = torch.tensor([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [19]:
# Accessing elements
print(mat1[1, 3])
print(mat1[1:3, 3:5])
print(mat1[1, :])

tensor(2328)
tensor([[2328, 2539],
        [6461, 2691]])
tensor([1478, 3877, 3674, 2328, 2539])


In [20]:
# Vectorized operations on rows or columns
print(mat1[0, :] + mat1[1, :])
print(mat1[:, 0] + mat1[:, 1])

tensor([1478, 3877, 3676, 2333, 2539])
tensor([   0, 5355, 5701, 4952, 6410, 5509,  324,    2, 5223, 5385])


In [21]:
# Vectorized operations on entire arrays
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = torch.tensor([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(a + b)

tensor([[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]])


### Example 2

In [22]:
# torch axis argument
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
    
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

tensor(45)
tensor([12, 15, 18])
tensor([ 6, 15, 24])


### Problem 4


Fill in the following cell to achieve the effect of the `for` for the array `mat1` above, store the maximum entry of each row of a list version of `mat1`:

```python
mat1 = [[   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]]
row_max = []
for row in mat1:
    row_max.append(max(row))
```

In [25]:
row_max = mat1.max(axis=1).values
print(row_max)

tensor([   5, 3877, 6461, 4787, 4802, 4979,  496,   27, 4174, 4665])


### Problem 5

Fill in the following cell to achieve the effect of the `for` for the array `mat1` above, store the index of the maximum entry of each row of a list version of `mat1`:

```python
mat1 = [[   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]]
index_max = []
for row in mat1:
    tmp = row.index(max(row))
    index_max.append(index_max)
```

Hint: the function `argmax()` in PyTorch may be helpful: https://pytorch.org/docs/stable/generated/torch.argmax.html, which can be either applied as a function or as a method for the tensor `a.argmax()` with an `axis=` argument.

In [26]:
index_max = mat1.argmax(axis=1)

print(index_max)

tensor([3, 1, 3, 3, 1, 3, 3, 3, 3, 3])


## Runtime Comparison

In [27]:
import time

We will need to be able to generate random numbers for hte next problem. `PyTorch` also all sorts of random number generator similar to `numpy.random` submodule. 

We can use `?` to access the documentation of every function, so keep it in mind for easy access to documentations! If we are in Colab or Visual Studio Code, hovering the mouse over a function pops up the documentation as well.

In [28]:
?torch.randn 


### Problem 6

Using `torch.randn` function, which takes in inputs `(n,m)`, to generate a random 2d array of `n` rows and `m` columns. 

Note: we should format the code as `torch.randn((2,5))` not `torch.randn(2,5)` if we want to generate a 2 by 5 random matrix.

In [29]:
def calculate_row_sums_loop(random_2d_array):
    """
    Fill in this function to calculate row sums of 2d_array using a for loop.
    """ 
    # your code here
    result = []
    for row in random_2d_array:
        result.append(sum(row))
        
    return result

In [30]:
def calculate_row_sums_vec(random_2d_array):
    """
    Fill in this function to calculate row sums of 2d_array 
    using pytorch builtin vectorized functions.
    """
    # your code here
    result = random_2d_array.sum(axis=1)
    return result

After you done with the functions above, run this to compare runtime of for loops and numpy functions. Play with the matrix dimesions to see the effect! Hint: for the non-vectorized function it should take

In [34]:
# generate a random 2d array
num_rows = 1000
num_cols = 1000
random_2d_array = generate_random_2d_array(num_rows, num_cols)

start = time.time()
# calculate row sums by for loop
calculate_row_sums_loop(random_2d_array)
end = time.time()
print(f"loop: {end - start} secs.")

start = time.time()
# calculate row sums by for np.sum
calculate_row_sums_vec(random_2d_array)
end = time.time()
print(f"vec: {end - start} secs.")

loop: 4.837149381637573 secs.
vec: 0.0010809898376464844 secs.


In [32]:
# extra cell
def generate_random_2d_array(num_rows, num_cols):
    return torch.randn((num_rows, num_cols))